

export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL";


export const ALL_TASK_REQUEST = "ALL_TASK_REQUEST";
export const ALL_TASK_SUCCESS = "ALL_TASK_SUCCESS";
export const ALL_TASK_FAIL = "ALL_TASK_FAIL";

export const SINGLE_TASK_REQUEST = "SINGLE_TASK_REQUEST";
export const SINGLE_TASK_SUCCESS = "SINGLE_TASK_SUCCESS";
export const SINGLE_TASK_FAIL = "SINGLE_TASK_FAIL";


export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_RESET = "UPDATE_TASK_RESET";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";
export const DELETE_TASK_RESET = "DELETE_TASK_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
